1.0 beta 15 - покрытие тестами составляет 27% (33/121) - доступна новая команда bridge выводит список доступных гостевых интерфейсов - исправлена ошибка, возникавшая при чтении данных из архива shadowsocks соединения - в скрипте kvas_ipset адрес 0.0.0.0 убран из добавления в таблицу ipset - доработан механизм установки AdGuard Home на локальное устройство - при запуске команды kvas dns, теперь выводится сервис-владелец DNS: dnsmasq, dnscrypt_proxy2, AdGuard Home - доработан скрипт kvas_adblock по обновлению списков рекламы в разрезе отработки различных ошибок.

diff --git a/opt/bin/kvas_adblock b/opt/bin/kvas_adblock
--- a/opt/bin/kvas_adblock
+++ b/opt/bin/kvas_adblock
@@ -1,31 +1,40 @@
 #!/bin/sh
-
 . /opt/bin/kvas_lib_main
 
-#adblock_file="/opt/etc/adblock.dnsmasq"
 tmp_path="/opt/tmp/adblock"
 tmp_file="/opt/tmp/hosts.tmp"
 adhosts_file="${tmp_path}/hosts"
-error_source="/opt/tmp/kvas.err.log"
 main_hosts_file="/opt/etc/hosts"
+dnsmasq_demon="/opt/etc/init.d/S56dnsmasq"
+error_source="/opt/tmp/kvas.err.log"
 ads_sources_file="/opt/etc/adblock.sources"
 grepv="#|^$|localhost| local|broadcasthost|loopback|localnet|mcastprefix|allnodes|allrouters|allhosts| 0.0.0.0"
+# блокируем различные популярные в РФ счетчики и определители IP
+cat <<EOF >> "${adhosts_file}"
+0.0.0.0 ezstat.ru
+0.0.0.0 iplogger.org
+0.0.0.0 2no.co
+0.0.0.0 iplogger.com
+0.0.0.0 iplogger.ru
+0.0.0.0 yip.su
+0.0.0.0 iplogger.co
+0.0.0.0 iplogger.info
+0.0.0.0 ipgrabber.ru
+0.0.0.0 ipgraber.ru
+0.0.0.0 iplis.ru
+0.0.0.0 02ip.ru
+EOF
 
-! [ -f "${ads_sources_file}" ] && error "Файл с ссылками на списки блокировки рекламы отсутствует."; exit 0
-
-exclude_com="$(cat < '/opt/etc/hosts.list' | tr -d '*' | sed ':a;N;$!ba;s/\n/$| /g')$"
-exclude_www="www.$(cat < '/opt/etc/hosts.list' | tr -d '*' | sed ':a;N;$!ba;s/\n/$| www./g')$"
-exclude_all="${exclude_com}|${exclude_www}"
-
-rm -rf "${tmp_path}"; mkdir -p "${tmp_path}"
-#cat /dev/null > "${adblock_file}"
-score=0
-hosts=0
-
+! [ -f "${ads_sources_file}" ] && {
+	error "Файл с ссылками на списки блокировки рекламы отсутствует.";
+	exit 1
+	}
+[ -d "${tmp_path}" ] && rm -rf "${tmp_path}"; mkdir -p "${tmp_path}"
 [ -f "${error_source}" ] && rm -f "${error_source}"
 
 [ -z "${1}" ] && echo "Загрузка хостов для блокировки из источников..."
 print_line
+score=0; hosts=0
 
 total=$(cat < "${ads_sources_file}" | sed '/^$/d; /^#/d' | wc -l )
 while read -r source || [ -n "${source}" ]; do
@@ -50,61 +59,80 @@ done < "${ads_sources_file}"
 printf "\n"
 print_line
 
-# блокируем различные популярные в РФ счетчики и определители IP
-cat <<EOF >> "${adhosts_file}"
-0.0.0.0 ezstat.ru
-0.0.0.0 iplogger.org
-0.0.0.0 2no.co
-0.0.0.0 iplogger.com
-0.0.0.0 iplogger.ru
-0.0.0.0 yip.su
-0.0.0.0 iplogger.co
-0.0.0.0 iplogger.info
-0.0.0.0 ipgrabber.ru
-0.0.0.0 ipgraber.ru
-0.0.0.0 iplis.ru
-0.0.0.0 02ip.ru
-EOF
-
 if [ -f ${error_source} ]; then
-	error "Следующие ссылки не корректны и содержат HTML код"
-	error " Отредактируйте должным образом ${ads_sources_file}"
+	mess_1="Следующие ссылки не корректны и содержат HTML код"
+	mess_2="Отредактируйте их должным образом ${ads_sources_file}"
+	error "${mess_1}"; error "${mess_2}"
+	logger "${mess_1}"; logger "${mess_2}"
 	print_line
+	echo errorrrrrrrrrrrr
 fi
 
 ready "Сортировка и удаление дубликатов"
 nlines_all=$(cat < "${adhosts_file}" | wc -l)
 cat < "${adhosts_file}" | sort -u > ${tmp_file}
-when_ok "ГОТОВО"
-
-ready "Исключаем из списка блокировки хосты из белого списка"
 nlines_sorted=$(cat < "${tmp_file}" | wc -l)
-cat < "${tmp_file}" | grep -vE "${exclude_all}" > "${adhosts_file}"
 when_ok "ГОТОВО"
 
-ready "Проверяем на ошибки скаченные файлы"
-nlines_excluded=$(cat < "${adhosts_file}" | wc -l)
-/opt/sbin/dnsmasq --test --hostsdir="${tmp_path}"  &> /dev/null
-if [ "$?" == "0" ]; then
+if [ -f "${main_hosts_file}" ]; then
+	exclude_com="$(cat < "${main_hosts_file}" | tr -d '*' | sed ':a;N;$!ba;s/\n/$| /g')$"
+	exclude_www="www.$(cat < "${main_hosts_file}" | tr -d '*' | sed ':a;N;$!ba;s/\n/$| www./g')$"
+	exclude_all="${exclude_com}|${exclude_www}"
+
+	ready "Исключаем из списка блокировки хосты из белого списка"
+	cat < "${tmp_file}" | grep -vE "${exclude_all}" > "${adhosts_file}"
 	when_ok "ГОТОВО"
-	logger "Рекламных хостов для блокировки добавлено $(dig_frm ${hosts}) шт."
+	rm "${tmp_file}"
+	nlines_excluded=$(cat < "${adhosts_file}" | wc -l)
+
 else
-	when_bad "ОШИБКИ"
-	error "Проверьте файл ${adhosts_file} на ошибки"
+	mv "${tmp_file}" "${adhosts_file}"
+	nlines_excluded="${nlines_all}"
 fi
+
+
+
+[ -f "${dnsmasq_demon}" ] && {
+	if grep -q alive "${dnsmasq_demon}"; then
+		ready "Проверяем на ошибки скаченные файлы"
+		/opt/sbin/dnsmasq_demon --test --hostsdir="${tmp_path}"  &> /dev/null
+		if [ "$?" == "0" ]; then
+			when_ok "ГОТОВО"
+			logger "Рекламных хостов для блокировки добавлено $(dig_frm ${hosts}) шт."
+		else
+			when_bad "ОШИБКИ"
+			mess="Проверьте файл ${adhosts_file} на ошибки"
+			error "${mess}"; logger "${mess}"
+		fi
+	fi
+}
 
 print_line
 nlines_srt=$((nlines_all - nlines_sorted))
 nlines_exc=$((nlines_sorted - nlines_excluded))
 
+mess="Скачено хостов для блокировки рекламы"
 nlines_all_txt=$(dig_frm "${nlines_all}")
+ready "${mess}"; when_alert "${nlines_all_txt}"
+logger "${mess} ${nlines_all_txt}"
+
+mess="Количество удаленных дубликатов"
 nlines_srt_txt=$(dig_frm "${nlines_srt}")
+ready "${mess}"; when_alert "${nlines_srt_txt}"
+logger "${mess} ${nlines_srt_txt}"
+
+mess="Исключено записей из списка блокировки"
 nlines_exc_txt=$(dig_frm "${nlines_exc}")
+ready "${mess}"; when_alert "${nlines_exc_txt}"
+logger "${mess} ${nlines_exc_txt}"
+
+mess="Добавлено всего хостов для блокировки рекламы"
 nlines_add_txt=$(dig_frm "${nlines_excluded}")
+ready "${mess}"; when_alert "${nlines_add_txt}"
+logger "${mess} ${nlines_add_txt}"
 
-ready "Скачено хостов для блокировки рекламы"; when_alert "${nlines_all_txt}"
-ready "Количество удаленных дубликатов"; when_alert "${nlines_srt_txt}"
-ready "Исключено записей из списка блокировки"; when_alert "${nlines_exc_txt}"
-ready "Добавлено всего хостов для блокировки рекламы"; when_alert "${nlines_add_txt}"
-
-/opt/etc/init.d/S56dnsmasq restart &> /dev/null
+[ -f "${dnsmasq_demon}" ] && {
+        if grep -q alive "${dnsmasq_demon}"; then
+                "${dnsmasq_demon}" restart &> /dev/null
+        fi
+} || exit 0
